## Feature Engineering

We created three new features by combining existing machine measurements to capture more meaningful operating conditions:

### 1. Temperature Difference (`temperature_difference_k`)

Calculated as:

Process Temperature − Air Temperature

This represents the temperature difference between the machine process and the surrounding environment, helping capture the machine's heat dissipation condition.

### 2. Power (`power_w`)

Calculated as:

Power = Torque × Angular Velocity

where:

Angular Velocity = RPM × (2π / 60)

This combines torque and rotational speed to represent the machine's overall mechanical power or operating load.

### 3. Tool Wear × Torque (`tool_wear_torque`)

Calculated as:

Tool Wear × Torque

This captures the combined effect of tool wear and mechanical load. A highly worn tool operating under high torque may experience greater mechanical stress and a higher risk of failure.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/processed/cleaned_df.csv")

In [4]:
df

,type,air_temperature_k,process_temperature_k,rotational_speed_rpm,torque_nm,tool_wear_min,machine_failure
0,M,298.1,308.6,1551,42.8,0,0
1,L,298.2,308.7,1408,46.3,3,0
2,L,298.1,308.5,1498,49.4,5,0
3,L,298.2,308.6,1433,39.5,7,0
4,L,298.2,308.7,1408,40.0,9,0
...,...,...,...,...,...,...,...
9995,M,298.8,308.4,1604,29.5,14,0
9996,H,298.9,308.4,1632,31.8,17,0
9997,M,299.0,308.6,1645,33.4,22,0
9998,H,299.0,308.7,1408,48.5,25,0
9999,M,299.0,308.7,1500,40.2,30,0

In [5]:
df["temperature_difference_k"] = (
    df["process_temperature_k"]
    - df["air_temperature_k"]
)

In [6]:

df["power_w"] = (
    df["torque_nm"]
    * df["rotational_speed_rpm"]
    * (2 * np.pi / 60)
)

In [7]:
df["tool_wear_torque"] = (
    df["tool_wear_min"]
    * df["torque_nm"]
)

In [8]:
df["type"] = df["type"].map({
    "L": 0,
    "M": 1,
    "H": 2
})

In [9]:
df

,type,air_temperature_k,process_temperature_k,rotational_speed_rpm,torque_nm,tool_wear_min,machine_failure,temperature_difference_k,power_w,tool_wear_torque
0,1,298.1,308.6,1551,42.8,0,0,10.5,6951.590560,0.0
1,0,298.2,308.7,1408,46.3,3,0,10.5,6826.722724,138.9
2,0,298.1,308.5,1498,49.4,5,0,10.4,7749.387543,247.0
3,0,298.2,308.6,1433,39.5,7,0,10.4,5927.504659,276.5
4,0,298.2,308.7,1408,40.0,9,0,10.5,5897.816608,360.0
...,...,...,...,...,...,...,...,...,...,...
9995,1,298.8,308.4,1604,29.5,14,0,9.6,4955.129373,413.0
9996,2,298.9,308.4,1632,31.8,17,0,9.5,5434.703963,540.6
9997,1,299.0,308.6,1645,33.4,22,0,9.6,5753.617506,734.8
9998,2,299.0,308.7,1408,48.5,25,0,9.7,7151.102638,1212.5
9999,1,299.0,308.7,1500,40.2,30,0,9.7,6314.601234,1206.0

In [12]:
df.to_csv("../data/processed/featured_data.csv", index=False)